#!/usr/bin/perl

use strict;
use warnings;
use Storable;

my $db = retrieve("/tmp/logwatch.db");

my %users;

print "Failed authentication attempts:\n";
foreach my $ip (keys(%{$db->{"ssh-illegal-user"}})) {
	my $v = $db->{"ssh-illegal-user"}->{$ip};
	print "   $ip: " . scalar(@{$v}) . "\n";
	map { $users{$_->{"data"}}++ } @{$v};
}

print "\n";

print "User attempt counts: \n";
foreach (sort { $users{$b} <=> $users{$a} || $a cmp $b } keys(%users)) {
	printf "%15s: %d\n", $_, $users{$_};
}
